import json
import os
import re
import sqlite3
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from groq import Groq

load_dotenv()

app = Flask(__name__)

DB_PATH = "provenance.db"

# ── Database ──────────────────────────────────────────────────────────────────

def init_db():
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS audit_log (
                id               INTEGER PRIMARY KEY AUTOINCREMENT,
                content_id       TEXT NOT NULL UNIQUE,
                creator_id       TEXT,
                timestamp        TEXT NOT NULL,
                content_preview  TEXT,
                llm_score        REAL,
                stylo_score      REAL,
                final_score      REAL,
                classification   TEXT,
                confidence_level TEXT,
                label_text       TEXT,
                short_text_flag  INTEGER DEFAULT 0,
                status           TEXT NOT NULL DEFAULT 'classified',
                appeal_reasoning TEXT,
                appeal_timestamp TEXT
            )
        """)


def log_submission(record: dict):
    with sqlite3.connect(DB_PATH) as conn:
        conn.execute(
            """
            INSERT INTO audit_log
                (content_id, creator_id, timestamp, content_preview,
                 llm_score, stylo_score, final_score, classification,
                 confidence_level, label_text, short_text_flag, status)
            VALUES
                (:content_id, :creator_id, :timestamp, :content_preview,
                 :llm_score, :stylo_score
                 , :final_score, :classification,
                 :confidence_level, :label_text, :short_text_flag, :status)
            """,
            record,
        )


def read_log(limit: int = 20) -> list[dict]:
    with sqlite3.connect(DB_PATH) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT * FROM audit_log ORDER BY id DESC LIMIT ?", (limit,)
        ).fetchall()
    return [dict(row) for row in rows]


init_db()

# ── Signal 1: LLM Classifier (Groq) ──────────────────────────────────────────

_groq = Groq(api_key=os.environ.get("GROQ_API_KEY"))

_LLM_PROMPT = """\
You are an expert at distinguishing human-written text from AI-generated text.

Analyze the following text and estimate the probability that it was generated by AI.

Return ONLY a valid JSON object with exactly these two fields:
- "ai_probability": a float from 0.0 to 1.0
    (0.0 = definitely human-written, 1.0 = definitely AI-generated)
- "reasoning": a SHORT quoted string (max 20 words) explaining your assessment

Important: the value of "reasoning" MUST be a properly quoted JSON string.

Example of correct output:
{{"ai_probability": 0.3, "reasoning": "Informal tone and personal anecdotes suggest human authorship."}}

Text:
\"\"\"
{content}
\"\"\""""


def classify_with_llm(text: str) -> tuple[float, str | None]:
    """Return (llm_score, reasoning). Falls back to (0.5, None) on any parse error."""
    prompt = _LLM_PROMPT.format(content=text)
    try:
        response = _groq.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
        )
        raw = response.choices[0].message.content.strip()
        # Strip markdown code fences if the model wraps the JSON
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)
        try:
            data = json.loads(raw)
            score = max(0.0, min(1.0, float(data["ai_probability"])))
            return score, data.get("reasoning")
        except (json.JSONDecodeError, KeyError, ValueError):
            # Fallback: extract the numeric value directly via regex
            m = re.search(r'"ai_probability"\s*:\s*([0-9.]+)', raw)
            if m:
                score = max(0.0, min(1.0, float(m.group(1))))
                return score, None
            return 0.5, None
    except Exception:
        return 0.5, None


# ── Confidence Scoring ────────────────────────────────────────────────────────

_LLM_WEIGHT   = 0.65
_STYLO_WEIGHT = 0.35


def compute_final_score(llm_score: float, stylo_score: float) -> float:
    return _LLM_WEIGHT * llm_score + _STYLO_WEIGHT * stylo_score


def classify(final_score: float) -> tuple[str, str]:
    """Return (classification, confidence_level)."""
    if final_score > 0.65:
        return "ai_generated", "high"
    if final_score < 0.35:
        return "human", "high"
    return "uncertain", "uncertain"


def generate_label(final_score: float) -> str:
    if final_score > 0.65:
        return (
            "Our automated analysis found strong signals that this content "
            "may be AI-generated. This is not a definitive finding — our system "
            "can be wrong, especially for polished or formally written human work. "
            "If you are the creator and believe this assessment is incorrect, "
            "you can submit an appeal."
        )
    if final_score < 0.35:
        return (
            "Our automated analysis found strong signals that this content was "
            "written by a human. This assessment is based on stylistic and semantic "
            "patterns and reflects our best confidence at this time."
        )
    return (
        "Our system could not determine with confidence whether this content "
        "was written by a human or generated by AI. The signals were mixed or "
        "inconclusive. If you are the creator, you may submit an appeal to "
        "provide additional context that can help with review."
    )


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
def submit():
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "JSON body required"}), 400

    content = (data.get("content") or data.get("text") or "").strip()
    if not content:
        return jsonify({"error": "content field is required and must not be empty"}), 400

    creator_id  = data.get("creator_id")
    content_id  = str(uuid.uuid4())
    word_count  = len(content.split())
    short_text  = word_count < 10

    # Very short texts skip the LLM and return uncertain
    if short_text:
        llm_score = 0.5
    else:
        llm_score, _ = classify_with_llm(content)

    stylo_score  = 0.5  # placeholder — Signal 2 added in M4
    final_score  = compute_final_score(llm_score, stylo_score)
    classification, confidence_level = classify(final_score)
    label_text   = generate_label(final_score)

    log_submission({
        "content_id":       content_id,
        "creator_id":       creator_id,
        "timestamp":        datetime.now(timezone.utc).isoformat(),
        "content_preview":  content[:200],
        "llm_score":        llm_score,
        "stylo_score":      stylo_score,
        "final_score":      round(final_score, 4),
        "classification":   classification,
        "confidence_level": confidence_level,
        "label_text":       label_text,
        "short_text_flag":  int(short_text),
        "status":           "classified",
    })

    return jsonify({
        "content_id":       content_id,
        "classification":   classification,
        "confidence_score": round(final_score, 4),
        "confidence_level": confidence_level,
        "label_text":       label_text,
        "signals": {
            "llm_score":   round(llm_score, 4),
            "stylo_score": stylo_score,
        },
        "short_text_warning": short_text,
        "status":             "classified",
        "appeal_url":         f"/appeal/{content_id}",
    })


@app.route("/log", methods=["GET"])
def view_log():
    try:
        limit = max(1, min(int(request.args.get("limit", 20)), 100))
    except ValueError:
        limit = 20
    entries = read_log(limit)
    return jsonify({"entries": entries, "total": len(entries)})


if __name__ == "__main__":
    app.run(port=5001, debug=True)
