_LLM_WEIGHT   = 0.65
_STYLO_WEIGHT = 0.35


def compute_final_score(llm_score: float, stylo_score: float) -> float:
    return _LLM_WEIGHT * llm_score + _STYLO_WEIGHT * stylo_score


def classify(final_score: float) -> tuple[str, str]:
    """Return (classification, confidence_level)."""
    if final_score > 0.65:
        return "ai_generated", "high"
    if final_score < 0.35:
        return "human", "high"
    return "uncertain", "uncertain"


def generate_label(final_score: float) -> str:
    if final_score > 0.65:
        return (
            "Our automated analysis found strong signals that this content "
            "may be AI-generated. This is not a definitive finding — our system "
            "can be wrong, especially for polished or formally written human work. "
            "If you are the creator and believe this assessment is incorrect, "
            "you can submit an appeal."
        )
    if final_score < 0.35:
        return (
            "Our automated analysis found strong signals that this content was "
            "written by a human. This assessment is based on stylistic and semantic "
            "patterns and reflects our best confidence at this time."
        )
    return (
        "Our system could not determine with confidence whether this content "
        "was written by a human or generated by AI. The signals were mixed or "
        "inconclusive. If you are the creator, you may submit an appeal to "
        "provide additional context that can help with review."
    )
