import json
import os
import re
import statistics

from groq import Groq

_groq = Groq(api_key=os.environ.get("GROQ_API_KEY"))

_LLM_PROMPT = """\
You are an expert at distinguishing human-written text from AI-generated text.

Analyze the following text and estimate the probability that it was generated by AI.

Return ONLY a valid JSON object with exactly these two fields:
- "ai_probability": a float from 0.0 to 1.0
    (0.0 = definitely human-written, 1.0 = definitely AI-generated)
- "reasoning": a SHORT quoted string (max 20 words) explaining your assessment

Important: the value of "reasoning" MUST be a properly quoted JSON string.

Example of correct output:
{{"ai_probability": 0.3, "reasoning": "Informal tone and personal anecdotes suggest human authorship."}}

Text:
\"\"\"
{content}
\"\"\""""


def classify_with_llm(text: str) -> tuple[float, str | None]:
    """Signal 1: LLM-based holistic classifier via Groq.
    Returns (llm_score, reasoning). Falls back to (0.5, None) on any error."""
    prompt = _LLM_PROMPT.format(content=text)
    try:
        response = _groq.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
        )
        raw = response.choices[0].message.content.strip()
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)
        try:
            data = json.loads(raw)
            score = max(0.0, min(1.0, float(data["ai_probability"])))
            return score, data.get("reasoning")
        except (json.JSONDecodeError, KeyError, ValueError):
            m = re.search(r'"ai_probability"\s*:\s*([0-9.]+)', raw)
            if m:
                return max(0.0, min(1.0, float(m.group(1)))), None
            return 0.5, None
    except Exception:
        return 0.5, None


# ── Signal 2: Stylometric Heuristics ─────────────────────────────────────────

def _sentence_length_score(text: str) -> float:
    """Low CV (uniform lengths) → 1.0 (AI-like). High CV → 0.0 (human-like)."""
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if len(sentences) < 2:
        return 0.5
    lengths = [len(s.split()) for s in sentences]
    mean = statistics.mean(lengths)
    if mean == 0:
        return 0.5
    cv = statistics.stdev(lengths) / mean
    return max(0.0, min(1.0, 1.0 - (cv / 0.8)))


def _ttr_score(text: str) -> float:
    """Low TTR (less unique vocab) → 1.0 (AI-like). High TTR → 0.0 (human-like).
    Suppressed for texts under 80 words — short passages have naturally high TTR
    regardless of authorship, making the signal uninformative below this threshold."""
    words = re.findall(r'\b\w+\b', text.lower())
    if len(words) < 80:
        return 0.5
    ttr = len(set(words)) / len(words)
    # Calibrated to realistic TTR ranges for 80-300 word passages:
    # AI prose typically 0.55-0.70, human prose 0.65-0.85
    return max(0.0, min(1.0, (0.72 - ttr) / 0.30))


def _punctuation_score(text: str) -> float:
    """Few expressive punctuation types → 1.0 (AI-like). Many types → 0.0 (human-like)."""
    expressive = set('—–;…!?')
    count = len({c for c in text if c in expressive})
    return max(0.0, 1.0 - count / 3.0)


def _word_length_score(text: str) -> float:
    """Short avg word length → 0.0 (human-like). Long → 1.0 (AI-like)."""
    words = re.findall(r'\b\w+\b', text)
    if not words:
        return 0.5
    avg_len = sum(len(w) for w in words) / len(words)
    return max(0.0, min(1.0, (avg_len - 4.0) / 2.0))


def compute_stylo_score(text: str) -> float:
    """Signal 2: average of four normalized sub-signals (0 = human-like, 1 = AI-like)."""
    sub_scores = [
        _sentence_length_score(text),
        _ttr_score(text),
        _punctuation_score(text),
        _word_length_score(text),
    ]
    return round(sum(sub_scores) / len(sub_scores), 4)


# ── Signal 3: Formality / Register ───────────────────────────────────────────

_CONTRACTIONS_RE = re.compile(
    r"\b(I'm|I've|I'd|I'll|you're|you've|you'd|you'll|"
    r"he's|she's|it's|we're|we've|we'd|we'll|they're|they've|they'd|they'll|"
    r"that's|there's|here's|what's|who's|can't|won't|don't|didn't|doesn't|"
    r"isn't|aren't|wasn't|weren't|hasn't|haven't|hadn't|wouldn't|couldn't|"
    r"shouldn't|mustn't|shan't|\w+n't)\b",
    re.IGNORECASE,
)

_INFORMAL_WORDS = {
    'gonna', 'wanna', 'kinda', 'sorta', 'gotta', 'lemme',
    'dunno', 'ya', 'yep', 'nope', 'okay', 'yeah', 'hmm', 'ugh',
}


def compute_formality_score(text: str) -> float:
    """Signal 3: register-based formality detector (0 = human-like, 1 = AI-like).

    AI-generated text almost never uses contractions or informal tokens.
    Measures the ratio of contractions + informal words to total words.
    0% informal → formal/AI-like → 1.0
    2%+ informal → casual/human-like → 0.0
    """
    words = re.findall(r"\b\w+\b", text.lower())
    if not words:
        return 0.5
    contraction_count = len(_CONTRACTIONS_RE.findall(text))
    informal_count = sum(1 for w in words if w in _INFORMAL_WORDS)
    informal_ratio = (contraction_count + informal_count) / len(words)
    return round(max(0.0, min(1.0, 1.0 - informal_ratio / 0.02)), 4)
